### ISSUE TITLE
Doesn't run on Android

### ISSUE THREAD

**Issue by xingxiaoxiong** [oddmax/oddmax-match3-mvc-ecs-example#1]
I am using Unity 2020.3.13f1 which is the version this project was originally created for.
In the Build Settings, Texture Compression was set to ASTC.
The game turns into a black screen after the made with Unity logo disappears.

**Comment by oddmax** [comment]
Unfortunately, I do not have an Android device to test it at the moment. I have updated the version to 2021.3.25f1, perhaps it would fix this issue. If not, write me and I'll try to take a look :)

**Comment by xingxiaoxiong** [comment]
Sorry it was my fault. It turned out I didn't build the addressables. 
After building them with Build > New Build > Default Build Script on the Addressables Groups window, I was able to build the game for both Windows and Android. 
 
BTW, have you considered port this project to ECS 1.0?
Thank you so much for making this project open source.
